version: "3.8"
services:
  tikeeti:
    build: .
    image: tikeeti
    restart: "always"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      db:
        condition: service_started
    environment:
      POSTGRES_HOST: db

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: "always"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${tikeeti}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: